#!/bin/bash

echo "========================================="
echo "  Firebase Deployment Script"
echo "========================================="
echo ""
echo "Step 1: Create Firebase Project"
echo "Go to: https://console.firebase.google.com/"
echo "Click: Add project"
echo "Name: ai-resume-builder"
echo ""
echo "Step 2: Initialize Firebase in this directory"
echo "Run: firebase init"
echo "- Select: Functions, Hosting"
echo "- Choose: Use existing project > Select your new project"
echo "- Language: Python"
echo "- Source directory: . (current)"
echo "- Public directory: public"
echo ""
echo "Step 3: Set Environment Variables"
echo "Run: firebase functions:config:set xai.api_key=\"YOUR_GROK_API_KEY\""
echo ""
echo "Step 4: Deploy"
echo "Run: firebase deploy"
echo ""
echo "========================================="
echo "  Quick Deploy (Hosting Only)"
echo "========================================="
echo ""
echo "If you just want to deploy the static site without backend:"
echo "Run: firebase deploy --only hosting"
echo ""
